[[DecompUtil]]
arch = "aarch64"
git-tree-sha1 = "85bfbbcf901627f121cb44ee1d640c32ad9e0959"
os = "macos"

    [[DecompUtil.download]]
    sha256 = "89c524b6f16b8ba409955538a7a46a4622812a6ddb54424d064cc72256106c6a"
    url = "https://github.com/dev10110/LibDecompUtil_jll.jl/releases/download/DecompUtil-v0.1.0+0/DecompUtil.v0.1.0.aarch64-apple-darwin.tar.gz"
[[DecompUtil]]
arch = "x86_64"
git-tree-sha1 = "74b87027a5b9273fe5ffe1fcb4305f25c062dfc5"
os = "macos"

    [[DecompUtil.download]]
    sha256 = "a6ec4a8bac6c2214affecba2ff5e124bc4753118701f6f821b9a6793bb25f6a4"
    url = "https://github.com/dev10110/LibDecompUtil_jll.jl/releases/download/DecompUtil-v0.1.0+0/DecompUtil.v0.1.0.x86_64-apple-darwin.tar.gz"
