# Autogenerated wrapper script for DecompUtil_jll for aarch64-apple-darwin
export libdecomputil

JLLWrappers.@generate_wrapper_header("DecompUtil")
JLLWrappers.@declare_library_product(libdecomputil, "@rpath/libdecomputil.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libdecomputil,
        "lib/libdecomputil.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
